# Solution (1)

In [2]:
import numpy as np

In [3]:
A = np.array([[1, -3, 3], [0, -5, 6], [0, -3, 4]], dtype=np.float64)

In [4]:
A

array([[ 1., -3.,  3.],
       [ 0., -5.,  6.],
       [ 0., -3.,  4.]])

## (i) QR decomposition

In [5]:
Q, R = np.linalg.qr(A)

In [6]:
print(f'Q:\n{Q}\n')
print(f'R:\n{R}\n')

Q:
[[ 1.          0.          0.        ]
 [ 0.         -0.85749293 -0.51449576]
 [ 0.         -0.51449576  0.85749293]]

R:
[[ 1.         -3.          3.        ]
 [ 0.          5.83095189 -7.20294058]
 [ 0.          0.          0.34299717]]



In [7]:
Q @ R

array([[ 1., -3.,  3.],
       [ 0., -5.,  6.],
       [ 0., -3.,  4.]])

## (ii) If A is diagonalizable, then express A as A = P DP −1 , where D is a diagonal matrix.

In [8]:
eigenvalues, eigenvectors = np.linalg.eig(A)

print(f'eigenvalues:\n{eigenvalues}\n')
print(f'eigenvectors:\n{eigenvectors}\n')

eigenvalues:
[ 1. -2.  1.]

eigenvectors:
[[ 1.         -0.40824829  0.        ]
 [ 0.         -0.81649658 -0.70710678]
 [ 0.         -0.40824829 -0.70710678]]



In [ ]:
P = eigenvectors    # A is diagonalizable as eigenvectors form as linearly independent basis of R^3
D = np.diag(eigenvalues)
P_inv = np.linalg.inv(P)

print(f'P:\n{P}\n')
print(f'D:\n{D}\n')
print(f'P_inv:\n{P_inv}\n')

P:
[[ 1.         -0.40824829  0.        ]
 [ 0.         -0.81649658 -0.70710678]
 [ 0.         -0.40824829 -0.70710678]]

D:
[[ 1.  0.  0.]
 [ 0. -2.  0.]
 [ 0.  0.  1.]]

P_inv:
[[ 1.         -1.          1.        ]
 [-0.         -2.44948974  2.44948974]
 [-0.          1.41421356 -2.82842712]]



In [10]:
# A = P @ D @ P^-1
P @ D @ P_inv

array([[ 1., -3.,  3.],
       [ 0., -5.,  6.],
       [ 0., -3.,  4.]])

## (iii) Singular Value Decomposition (SVD)

In [13]:
U, s, Vt = np.linalg.svd(A, full_matrices=False)

print(f'U:\n{U}\n')
print(f's:\n{s}\n')
print(f'Vt:\n{Vt}\n')

U:
[[ 0.4181953   0.90453403  0.08325185]
 [ 0.76535052 -0.30151134 -0.56862069]
 [ 0.48923539 -0.30151134  0.81837623]]

s:
[10.19615242  1.          0.19615242]

Vt:
[[ 0.04101501 -0.64230549  0.76535052]
 [ 0.90453403 -0.30151134 -0.30151134]
 [ 0.42442426  0.70465209  0.56862069]]



In [ ]:
# sigma = np.diag(s)
# A = U @ sigma @ Vt
U @ np.diag(s) @ Vt

array([[ 1.00000000e+00, -3.00000000e+00,  3.00000000e+00],
       [ 2.74997135e-18, -5.00000000e+00,  6.00000000e+00],
       [ 3.55028220e-17, -3.00000000e+00,  4.00000000e+00]])

# Solution 3

In [15]:
A = np.array([[2, 1, 0], [1, 3, 1], [0, 1, 2]], dtype=np.float64)
B = np.array([[1, 0, 1], [0, 1, 0], [1, 0, 1]], dtype=np.float64)
C = np.array([[1, 2, 0], [0, 1, 1], [2, 0, 1]], dtype=np.float64)
D = np.array([[4, 1, 0], [1, 4, 1], [0, 1, 3]], dtype=np.float64)

In [17]:
det_A = np.linalg.det(A)
# So, A is invertible
print(f'det_A: {det_A}\n')

det_A: 8.000000000000002



In [18]:
f = np.array([1, 2, 3], dtype=np.float64)
g = np.array([4, 5, 6], dtype=np.float64)

In [19]:
A_inv = np.linalg.inv(A)

schur_complement_A = D - C @ A_inv @ B

schur_complement_A_inv = np.linalg.inv(schur_complement_A)

In [20]:
y = schur_complement_A_inv @ (g - C @ A_inv @ f)
x = A_inv @ (f - B @ y)

print(f'x:\n{x}\n')
print(f'y:\n{y}\n')

x:
[-5.54545455  4.24242424 -4.54545455]

y:
[ 0.42424242 -0.63636364  7.42424242]



# Solution 2

In [ ]:
def f(n):
    '''
    f(n) is used to calculate y_n for given x_n
    we'll take n = -8 to 8 (we don't start from 0 to account for -ve x)
    '''
    return np.sin((n * np.pi) / 8)

In [ ]:
b = [f(n) for n in range(-8, 9, 1)] # b's are the y values
b = np.array(b, dtype=np.float64)
b

array([-1.22464680e-16, -3.82683432e-01, -7.07106781e-01, -9.23879533e-01,
       -1.00000000e+00, -9.23879533e-01, -7.07106781e-01, -3.82683432e-01,
        0.00000000e+00,  3.82683432e-01,  7.07106781e-01,  9.23879533e-01,
        1.00000000e+00,  9.23879533e-01,  7.07106781e-01,  3.82683432e-01,
        1.22464680e-16])

In [ ]:
A = []
for n in range(-8, 9, 1):
    a = []
    x = (n * np.pi) / 8
    for i in range(0, 6):
        a.append(x**i)
    A.append(a)

A = np.array(A, dtype=np.float64) # each row corresponds to each x_n

In [ ]:
def lss(A, b):
    '''
    Uses pseudo inverse of A (obtained from SVD) to get LSS
    x* (lss) = A_pinv @ b
    '''
    U, s, Vt = np.linalg.svd(A)
    m, n = A.shape
    s_inv = np.zeros((n, m), dtype=np.float64)
    for i in range(len(s)):
        if s[i] > 1e-8:
            s_inv[i, i] = 1.0 / s[i]
    
    A_pinv = Vt.T @ s_inv @ U.T
    
    x = A_pinv @ b

    return x

In [51]:
x = lss(A, b)

In [ ]:
print(f'x:\n{x}\n') # These are the coeffs' of the 5th degree polynomial from a_0 to a_5

x:
[-7.07312037e-15  9.85486423e-01  2.15035896e-15 -1.53808246e-01
 -1.70192204e-16  5.47847427e-03]



## Problem (2) Final Answer

Take f(x) = a0 + a1 * x + a2 * x^2 + a3 * x^3 + a4 * x^4 + a5 * x^5

x:
[-7.07312037e-15  9.85486423e-01  2.15035896e-15 -1.53808246e-01
 -1.70192204e-16  5.47847427e-03] = (a0, a1, a2, a3, a4, a5)

In [56]:
# check
def f1(c):
    res = 0
    for i in range(6):
        res += (c**i) * x[i]
    return res

In [ ]:
f1((5 * np.pi) / 8) # which almost matches for n = 5

0.930571791752186

In [58]:
f1((6 * np.pi) / 8) # which almost matches for n = 6

0.7079132194983795